### PR TITLE
Add documentaion for distanct AOIs for grid generation 

### LINKED ISSUE #35: Optimizing grid tile generation
I think there’s room for further optimization especially for `generate_grids` in the `GridGenerator` class. Right now the grid tiles are first generated across the entire span of `xrange` and `yrange` and then filtered out after. While this isn’t an issue for very coarse grids, this can easily run into runtime and memory issues for fine grids.

**Instead of generating all the tiles and then filtering after, we can generate only the grid tiles we need.**

1. This drastically saves on memory since our gdf won’t need to store tiles it doesn’t need.
2. This saves on runtime since we don’t need to generate unnecessary tiles, and don’t need to reproject unnecessary tiles.

**To determine which grid tiles to generate in the first place, we can use the cheapest possible geometric operations.**

1. Looping through `xrange` and `yrange` and intersecting tiles with the gdf’s `unary_union` can be expensive since the `unary_union` is a single geometry most likely has a large number of points.
2. We can instead generate tiles per polygon within the gdf. (If there are multipolygons we can explode to polygons). Per polygon, we can:
    1. Find the bounding box of the polygon. (should be cheap)
    2. Determine which tiles are within the polygon’s bounding box. (should be cheap since you don’t need to use shapely operations)
    3. Check which tiles are within the polygon itself by doing an intersection. (this is the most computationally expensive part but mitigated since we have less tiles to compare with, and a single polygon should have less points than the unary union)
    4. Avoid generating tiles that have already been generated. (can be a quick Python set lookup) This is relevant in cases where two polygons share the same tiles. 

Can make a PR for this too!

### LINKED ISSUE #59: Fix issue with grid generator when mask returns all false but are within bounds
In lines
https://github.com/thinkingmachines/geowrangler/blob/a918c669d758b8c1a64859777294602359606b31/geowrangler/grids.py#L29-L36

there is a case the resulting x_mask returns false if x_min and x_max, the bounds of the aoi, is less then the cell size
```
self.x_min is 12621582.219997052
self.x_max is 14243844.181000795
cell_size = 100
x_min = 13762392.958057601
x_max = 13762473.616812669
```

in this scenario, the following returns an empty array
```
 xrange = np.arange(self.x_min, self.x_max, cell_size)
 np.nonzero(x_mask)
```

the solution is to add a buffer to the x_max
```
 x_mask = (xrange >= x_min) & (xrange <= x_max + cell_size)
```

### LINKED ISSUE #60: Catch case where the aoi is ouside the bounds of the grid generator
The following errors out if no polygons/cells are within the aoi
https://github.com/thinkingmachines/geowrangler/blob/a918c669d758b8c1a64859777294602359606b31/geowrangler/grids.py#L107-L117
Catch instances like this making empty dataframes if polygon is nullish
```
    if polygons:
        dest = GeoDataFrame(polygons, geometry="geometry", crs=self.grid_projection)
        dest_reproject = dest.to_crs(self.gdf.crs)
        final = dest_reproject[dest_reproject.intersects(self.gdf.unary_union)]
        return final
    else:
        return GeoDataFrame({"x":[], "y":[], "geometry":[]}, geometry="geometry", crs=self.gdf.crs)
```

### PR DESCRIPTION
**Pull request by jtmiclat**
Closes #35
Closes #59 
Closes #60

### CODE REVIEW

**Comment by jtmiclat** [comment]
Hi @joshuacortez, Can you check if this aligns with what you mentioned in #35
https://geowrangler--pr55-docs-document-grid-p-q6ichi76.web.app/tutorial.grids.html#Generating-grids-for-multiple-distant-areas

**Comment by joshuacortez** [comment]
Hello @jtmiclat , tried to run the colab notebook but encountered an error when loading the admin_grids geojson. It couldn't find the file in the data directory. Thanks!

`grid_gdf = gpd.read_file("../data/region3_admin_grids.geojson")`

**Comment by jtmiclat** [comment]
@joshuacortez Fixed! Pls try it out again https://colab.research.google.com/github/thinkingmachines/geowrangler/blob/docs/document-grid-perfomance/notebooks/tutorial.grids.ipynb

**Comment by joshuacortez** [comment]
Thanks for the corrections! 

I looked at it and the example of having a ~50 square AOIs (divided into large cells of 1km) might not be representative of some actual use cases? Curious about the performance of dividing irregularly shaped polygons across a country into granular cells (e.g. 100m instead of 1km). That's where performance concerns (speed, memory) might be more apparent. 

I can help out with this if ever too.

**Comment by jtmiclat** [comment]
@joshuacortez Can you provide some irregular polygons we can try?

**Comment by joshuacortez** [comment]
Alright, provided test polygon AOIs [in this GPKG file](https://drive.google.com/file/d/17s1_XVdISPmBQs946AVgwfE7olR0UUTs/view?usp=sharing)

Parameters I used: 
- PHL bounding box as custom boundaries [-236221.24150117,  507465.65086805, 1119703.39754333,
       2336815.97643073] in epsg:3123
- `cell_size` of 100 meters

Some benchmarked runtime results using previous code:
- ~40 sec for the first 100 AOIs
- ~43 min for all the AOIs

**Comment by jtmiclat** [comment]
@joshuacortez I ran the benchmark on colab (Single core with ~14GB ram). It is very similar to what you mentioned. Let me know if you have the VM information!  

Screenshot from 2022-06-30 08-43-22

**Comment by joshuacortez** [comment]
Awesome, thanks @jtmiclat! This looks pretty good.

**Comment by joshuacortez** [comment]
I wonder if it makes sense to have a function that takes in a geodataframe of multiple AOIs instead of manually iterating through each AOI and making separate geodataframes. I don't feel too strongly about this but might look "cleaner" from a user perspective

**Comment by jtmiclat** [comment]
Mov

> I wonder if it makes sense to have a function that takes in a geodataframe of multiple AOIs instead of manually iterating through each AOI and making separate geodataframes. I don't feel too strongly about this but might look "cleaner" from a user perspective
Moving this to the discussion! 
https://github.com/thinkingmachines/geowrangler/discussions/63

**Review by butchtm — APPROVED** [review]

**Pull request merged**
