### PR TITLE
Fix/tutorial grids nbdev tests

### PR DESCRIPTION
**Pull request by butchtm**
* Fixed notebook tests for tutorial grids.
* Cleanup repeated instantiation of grid generator for 1k
* Minor doc improvements

### CODE REVIEW

**Review by jtmiclat — COMMENTED** [review]
Havent look too much into but getting the following errors
```
converting: /home/jt/repos/geowrangler/notebooks/00_validation.ipynb
Conversion failed on the following:
tutorial.grids.ipynb
```

**Comment by jtmiclat** [comment]
it seems to forcing to

```converting: /home/jt/repos/geowrangler/notebooks/tutorial.grids.ipynb
No such kernel named geowrangler
```
https://github.com/jupyter/nbclient/blob/main/nbclient/client.py#L181

**Comment by butchtm** [comment]
I think I encountered that bug before. I'll try adding a check in the future. The problem is the notebook metadata for the kernelspec hardcodes the kernel name w/ch is not present in the github build env. Will fix with  another commit.

**Comment by butchtm** [comment]
the last commit  (replace hardcoded kernel name) fixed the build problem. fyi @jtmiclat

**Review by jtmiclat — APPROVED** [review]

**Pull request merged**
